spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        - id: kyc-service
          uri: lb://kyc-service
          predicates:
            - Path=/kyc/**

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/admin/**

        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email/**

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**

        - id: customer-support
          uri: lb://customer-support
          predicates:
            - Path=/support/**
          filters:
            - StripPrefix=1

        - id: customer-support-ws
          uri: lb:ws://customer-support
          predicates:
            - Path=/support/ws/**

        - id: kyc-health
          uri: lb://kyc-service
          predicates:
            - Path=/health/kyc
          filters:
            - RewritePath=/health/kyc, /actuator/health

        - id: email-health
          uri: lb://email-service
          predicates:
            - Path=/health/email
          filters:
            - RewritePath=/health/email, /actuator/health

server:
  port: 8080
  address: 0.0.0.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:9099/eureka
  instance:
    prefer-ip-address: true
