spring:
  application:
    name: eureka-registry

server:
  port: 9099
  address: 0.0.0.0
  servlet:
    context-path: /

  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
          defaultZone: http://eureka-server:9099/eureka
  server:
    enable-self-preservation: false
